# Generated by Django 4.1.3 on 2023-04-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appetizer',
            fields=[
                ('omenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Menu.omenu')),
            ],
            bases=('Menu.omenu',),
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('omenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Menu.omenu')),
            ],
            bases=('Menu.omenu',),
        ),
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('omenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Menu.omenu')),
            ],
            bases=('Menu.omenu',),
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('omenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Menu.omenu')),
            ],
            bases=('Menu.omenu',),
        ),
    ]
